commands = {
	'set_config': 'c',
	'get_config': 'C',
	'set_config_hash':'h',
	'get_config_hash':'H',
	'save_config': ':',
	'load_config': ';',
	'send_status_and_position': 'P',
	'unstuck': 'U',
	'motor': 'm',
	'keep_speed': 'M',
	'send_position': 'p',
	'set_speed': 'V',
	'set_rotation_speed': 'r',
	'relative_rotate': 'T',
	'absolute_rotate': 'A',
	'turn_and_go': 'G',
	'move_to': 'N',
	'curve': 'Q',
	'curve_relative': 'q',
	'diff_drive': 'L',
	'hard_stop': 'S',
	'motor_init': 'F',
	'soft_stop': 's',
	'smooth_stop': 't',
	'reset_driver': 'R',
	'kill_regulator': 'k',
	'forward': 'D',
	'forward_lazy': 'd',
	'set_position_and_orientation': 'I',
	'break': 'i',
	'linear_optocoupler': '-',
	'reset': '_',
	'L_resp': 'l'
	
}

messages = {
	'debug_encoder1': '1',
	'debug_encoder2': '2',
	'debug_encoder': '3',
	'send_status_and_position': 'P',
	'status_changed': 'p',
	'status_changed2': 'a',
	'begin_command': 'b',
	'encoder1_ready': '!',
	'encoder2_ready': '@',
	'debug_distance': 'D',
	'debug_rotation': 'R',
	'debug':'d',
	'debug2': ',',
	'debug3': '.',
	'debug4': '-'
}
